language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t russianbb/docker-ci-101 -f Dockerfile.dev .

script:
  - docker run -e CI=true russianbb/docker-ci-101 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-701540483008"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY