language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t russianbb/docker-ci-101 -f Dockerfile.dev .

script:
  - docker run -e CI=true russianbb/docker-ci-101 npm run test